name: Test neurocommand

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
    
jobs:
  test_neurocommand:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Test neurocommand version
      run: /bin/bash .github/workflows/test_neurocommand.sh
